### ISSUE TITLE
exec injects web3, artifacts and other objects, rather than making them globally available

### ISSUE THREAD

**Issue by travs** [trufflesuite/truffle-require#2]
*Code (two modules)*:
```js
//    ./sample.js
module.exports = function (callback) {
    var doesntmatter = require('./othermodule');
}

//    ./othermodule.js
module.exports = web3.eth.accounts[0];
```

*Run*: `truffle exec sample.js`

*Result*: 
```
Using network 'development'.

/Users/travis/github/example_truffle/othermodule.js:2
module.exports = web3.eth.accounts[0]
                 ^

ReferenceError: web3 is not defined
```
*Discussion*:
I expected `web3` to be available *globally* (i.e. also in `othermodule.js`). 

[Gitter chat between myself and @tcoulter](https://gitter.im/ConsenSys/truffle?at=58fa41dd8e4b63533def3ed4) (we discuss temporary workaround here too)

**Comment by tcoulter** [comment]
I've been noodling over this one, and I think this might need to be the default behavior. For instance, objects like `require` aren't actually global; instead, your code is wrapped in a function and the `require` object is passed to it. The same thing is true for Truffle's "injection" of `web3` and other objects: They're simply passed to the function as local objects. 

I'm unsure if we can or should make them completely global. For now I'm going to leave this behavior as it is, as it requires you to write everything *other than* the current script being run modularly (i.e., you need to pass in web3), which is probably the right way to do it anyway.

Happy to reconsider if there's another context or example I should informed of. Cheers!
